language: c
sudo: false

branches:
  only:
    - master

install:
    - source devtools/travis-ci/install_miniconda.sh
    - conda config --add channels omnia

script:
    - conda build --quiet devtools/conda-recipe
