package:
  name: msmb_data-dev
  version: "0.0.0"

source:
  path: ../../

test:
  requires:
    - python
    - mdtraj

about:
  home: https://github.com/msmbuilder
  license: LGPLv2.1+
  summary: 'Testing data for MSMBuilder'
